### ISSUE TITLE
Error: name 'get_playlist_data' is not defined

### ISSUE THREAD

**Issue by Faheem2k19** [adi-txt/spotify-music-discovery#4]
After running the first cell if I provide a URL from my Spotify playlist in the input box, I get this error message. Any Solution?

**Comment by Arian-Rahman** [comment]
Try running VPN on your pc since spotify doesn't support most countries

**Comment by Arian-Rahman** [comment]
If that doesn't fix it , chances are you didn't go through the setup process properly , especially the 5th step .

**Comment by Faheem2k19** [comment]
> Try running VPN on your pc since spotify doesn't support most countries

I'm running Spotify on my machine every day without facing the country restriction issues. Though it required vpn when I first installed and tried to log in. But it's fine now.

**Comment by Faheem2k19** [comment]
It's working now. I forgot to run the very first cell of the "get_spotify_data" file.
